# Generated by Django 5.2.11 on 2026-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_table',
            name='certificate',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert_table',
            name='certificate1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expert_table',
            name='certificate2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
