# Generated by Django 5.2.11 on 2026-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expert_table_certificate_expert_table_certificate1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips_table',
            name='video',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
